swagger: '2.0'
info:
  title: Bank Argent API documentation 2/2
  description: Contains all available API endpoints in this codebase for account
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/{accountId}:
    get:
      security:
        - Bearer: []  # Utilisation de la sécurité basée sur les tokens Bearer
      tags:
        - Account details  # Tag pour catégoriser cet endpoint
      summary: Find account's last transactions
      description: API for fetching last transactions
      parameters:
        - in: header
          type: string
          name: Authorization  # JWT Token nécessaire pour l'autorisation
          description: Attach Bearer JWT Token
          required: true
        - name: accountId
          in: path  # Paramètre dans le chemin de l'URL
          description: Id of account
          required: true
          type: string
        - name: period
          in: body  # Paramètre dans le corps de la requête
          required: true
          description: Current Month
          schema:
            $ref: '#/definitions/TransactionsPeriod'  # Référence à la définition du schéma pour la période
      produces:
        - application/json  # Le type de réponse produit
      responses:
        '200':
          description: Successfully
          schema:
            $ref: '#/definitions/LastTransactions'  # Référence au schéma de la réponse en cas de succès
        '400':
          description: Invalid Fields
        '401':
          description: Invalid Token
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

  /user/{accountId}/{transactionId}:
    get:
      security:
        - Bearer: []  # Utilisation de la sécurité basée sur les tokens Bearer
      tags:
        - Transaction details  # Tag pour catégoriser cet endpoint
      summary: Find transaction by Id
      description: API for fetching one transaction details
      parameters:
        - in: header
          type: string
          name: Authorization  # JWT Token nécessaire pour l'autorisation
          description: Attach Bearer JWT Token
          required: true
        - name: accountId
          in: path  # Paramètre dans le chemin de l'URL
          description: Id of account
          required: true
          type: string
        - name: transactionId
          in: path  # Paramètre dans le chemin de l'URL
          description: Id of transaction
          required: true
          type: string
      produces:
        - application/json  # Le type de réponse produit
      responses:
        '200':
          description: Successfully
          schema:
            $ref: '#/definitions/Transaction'  # Référence au schéma de la réponse en cas de succès
        '400':
          description: Invalid Fields
        '401':
          description: Invalid Token
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []  # Utilisation de la sécurité basée sur les tokens Bearer
      tags:
        - Change transaction  # Tag pour catégoriser cet endpoint
      summary: Modify transaction details
      description: API for change transaction details
      parameters:
        - in: header
          type: string
          name: Authorization  # JWT Token nécessaire pour l'autorisation
          description: Attach Bearer JWT Token
          required: true
        - name: accountId
          in: path  # Paramètre dans le chemin de l'URL
          description: Id of account
          required: true
          type: string
        - name: transactionId
          in: path  # Paramètre dans le chemin de l'URL
          description: Id of transaction
          required: true
          type: string
        - in: body
          name: body  # Paramètre dans le corps de la requête
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionChange'  # Référence à la définition du schéma pour les modifications de transaction
      produces:
        - application/json  # Le type de réponse produit
      responses:
        '200':
          description: Transaction's modified
          schema:
            $ref: '#/definitions/Transaction'  # Référence au schéma de la réponse en cas de succès
        '400':
          description: Invalid Fields
        '401':
          description: Invalid Token
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey  # Définition du type de sécurité comme apiKey
    name: Authorization
    in: header
definitions:
  TransactionsPeriod:
    type: object  # Définition d'un objet pour la période des transactions
    properties:
      from:
        type: string
        format: date
        description: start date (30 days before)
        example: '2022-01-01'
      to:
        type: string
        format: date
        description: end date (today)
        example: '2022-02-01'
  LastTransactions:
    type: object  # Définition d'un objet pour les dernières transactions
    properties:
      TransactionId:
        type: string
        description: account's id
        example: "2357644"
      Date:
        type: string
        format: date
        example: "2022-01-20"
        description: transaction's date
      Description:
        type: string
        description: transaction's description
        example: "Golden Sun Bakery"
      Amount:
        type: number
        description: transaction's amount
        example: 2567
      Balance:
        type: number
        description: transaction's balance
        example: 145
  Transaction:
    type: object  # Définition d'un objet pour une transaction
    properties:
      TransactionId:
        type: string
        description: transaction's id
        example: "2357644"
      Date:
        type: string
        description: transaction's date
        example: "20-12-2021"
      Description:
        type: string
        description: transaction's description
        example: "Golden Sun Bakery"
      Amount:
        type: integer
        description: transaction's amount
        example: 5.65
      Balance:
        type: integer
        description: transaction's balance
        example: 2037.37
      TransactionType:
        type: string  # Notez la correction de l'espace en "Transaction type"
        description: transaction's type
        example: "Electronic"
      Category:
        type: string
        description: transaction's category
        example: "Food"
      Note:
        type: string
        description: transaction's note
        example: "Lunch for two"
  TransactionChange:
    type: object  # Définition d'un objet pour les modifications de transaction
    properties:
      Category:
        type: string
        description: transaction's category
        example: "Home"
      Note:
        type: string
        description: transaction's note
        example: "Ikea"
