swagger: '2.0'
info:
  title: Bank Argent API documentation 2/2
  description: Contains all available API endpoints in this codebase for transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transactions
      summary: Get transactions for the current month grouped by account
      description: Retrieve all transactions for the current month, grouped by account
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved transactions
          schema:
            type: object
            properties:
              accounts:
                type: array
                items:
                  $ref: '#/definitions/AccountTransactions'
        '500':
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Get transaction details
      description: Retrieve details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved transaction details
          schema:
            $ref: '#/definitions/TransactionDetails'
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

  /transactions/{transactionId}/category:
    post:
      tags:
        - Transactions
      summary: Add category and note to a transaction
      description: Add category and note to a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to add category and note
          required: true
          type: string
        - in: body
          name: body
          description: Category and note data to add
          required: true
          schema:
            $ref: '#/definitions/CategoryNote'
      produces:
        - application/json
      responses:
        '200':
          description: Category and note added successfully
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    put:
      tags:
        - Transactions
      summary: Update category and note of a transaction
      description: Update category and note of a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to update category and note
          required: true
          type: string
        - in: body
          name: body
          description: Updated category and note data
          required: true
          schema:
            $ref: '#/definitions/CategoryNote'
      produces:
        - application/json
      responses:
        '200':
          description: Category and note updated successfully
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    delete:
      tags:
        - Transactions
      summary: Delete category and note of a transaction
      description: Delete category and note of a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to delete category and note
          required: true
          type: string
      produces:
        - application/json
      responses:
        '204':
          description: Category and note deleted successfully
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

definitions:
  AccountTransactions:
    type: object
    properties:
      account_id:
        type: string
      transactions:
        type: array
        items:
          $ref: '#/definitions/TransactionSummary'

  TransactionSummary:
    type: object
    properties:
      transaction_id:
        type: string
      date:
        type: string
        format: date
      amount:
        type: number

  TransactionDetails:
    type: object
    properties:
      transaction_id:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      transaction_type:
        type: string
      category:
        type: string
      note:
        type: string

  CategoryNote:
    type: object
    properties:
      category:
        type: string
      note:
        type: string
