swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'https://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - https
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/RegisterRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/RegisterResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ProfileResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/ProfileUpdateRequest'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ProfileUpdateResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction?account_id=value&user_id=value:
    get:
      security:
        - Bearer: [ ]
      tags:
        - User Module
      summary: User Transactions API
      description: API for fetching the transactions during the current month in a user specific account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: query
          name: account_id
          required: true
          type: string
          description: The Account's ID
        - in: query
          name: user_id
          required: true
          type: string
          description: The User's ID
      produces:
        - application/json
      responses:
        '200':
          description: User's Account transactions for the current month retrieved successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction?account_id=value&transaction_id=value:
    get:
      security:
        - Bearer: [ ]
      tags:
        - User Module
      summary: User Transactions API
      description: API for fetching a unique transaction in a user specific account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: query
          name: account_id
          required: true
          type: string
          description: The Account's ID
        - in: query
          name: transaction_id
          required: true
          type: string
          description: The Transaction's ID
      produces:
        - application/json
      responses:
        '200':
          description: User's Account unique transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction:
    put:
      security:
        - Bearer: [ ]
      tags:
        - User Module
      summary: User Transactions API
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: The transaction that need to be updated and which field will be changed
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdateRequest'
      produces:
        - application/json
      responses:
        '200':
          description: User's transaction updated successully
          schema:
            $ref: '#/definitions/TransactionUpdateResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  LoginRequest:
    properties:
      email:
        type: string
        format: email
        description: User's email
        example: tony@stark.com
      password:
        type: string
        format: password
        description: User's password
        example: sup3rstr0ngpassw0rd
  LoginResponse:
    type: object
    properties:
      status:
        type: integer
        description: Response code from the API
        example: 200
      message:
        type: string
        description: Message from the API
        example: Token successfully retrieved!
      body:
        type: object
        properties:
          token:
            type: string
            description: Token created by the API
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGNjMDAwMzcyNGUxMGM4MjFjZmI1NSIsImlhdCI6MTY0NjMwMzYyMSwiZXhwIjoxNjQ2MzkwMDIxfQ.ERZlN7BaKTPH1bhddTP3yUratam2YtyVWki7MUKY_Ik
  RegisterRequest:
    type: object
    properties:
      email:
        type: string
        format: email
        description: User's email
        example: john_doe@example.com
      password:
        type: string
        format: password
        description: User's password
        example: sup3rstr0ngpassw0rd
      lastName:
        type: string
        description: User's first name
        example: John
      firstName:
        type: string
        description: User's last name
        example: Doe
  RegisterResponse:
    type: object
    properties:
      status:
        type: integer
        description: Response code from the API
        example: 200
      message:
        type: string
        description: Response message from the API
        example: User successfully registered!
      body:
        type: object
        properties:
          _id:
            type: string
            format: uuid
            description: User's UUID
            example: 620cc0003724e10c821cfb56
          email:
            type: string
            format: email
            description: User's email
            example: john_doe@example.com
          password:
            type: string
            description: Salted password
            example: $2b$12$EqaMrYkdSlE78OoSA31sNuBytdwwNuNCzgEJuTZLxzWlmgEnWBGVa
          firstName:
            type: string
            description: User's first name
            example: John
          lastName:
            type: string
            description: User's last name
            example: Doe
          createdAt:
            type: string
            format: date-time
            description: User's date creation
            example: 2022-02-16T09:12:32.769+00:00
          updatedAt:
            type: string
            format: date-time
            description: User's date update
            example: 2022-02-16T09:12:32.769+00:00
          __v:
            type: integer
  ProfileResponse:
    type: object
    properties:
      status:
        type: integer
        description: Response status code from the API
        example: 200
      message:
        type: string
        description: Response message from the API
        example: User's profile successfully retrieved!
      body:
        type: object
        properties:
          email:
            type: string
            format: email
            description: User's email
            example: tony@stark.com
          firstName:
            type: string
            description: User's first name
            example: Tony
          lastName:
            type: string
            description: User's last name
            example: Stark
          accounts:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: Account UUID
                  example: 620cdcfd11fbc30d0747af9d
                title:
                  type: string
                  description: Account title
                  example: Argent Bank Checking
                balance:
                  type: integer
                  description: Amount of money in this account in cents
                  example: 208979
                description:
                  type: string
                  description: Type of the account
                  example: Available Balance
          createdAt:
            type: string
            format: date-time
            description: User's date creation
            example: 2022-02-16T09:12:32.766+00:00
          updatedAt:
            type: string
            format: date-time
            description: User's date update
            example: 2022-02-16T09:12:32.766+00:00
          id:
            type: string
            format: uuid
            description: User's UUID
            example: 620cc0003724e10c821cfb56
  ProfileUpdateRequest:
    type: object
    properties:
      firstName:
        type: string
        description: User's first name
        example: John
      lastName:
        type: string
        description: User's last name
        example: Doe
  ProfileUpdateResponse:
    type: object
    properties:
      status:
        type: integer
        description: Response code from the API
        example: 200
      message:
        type: string
        description: Response message from the API
        example: User's profile successfully updated!
      body:
        type: object
        properties:
          email:
            type: string
            format: email
            description: User's email
            example: tony@stark.com
          firstName:
            type: string
            example: Tony
            description: User's first name
          lastName:
            type: string
            example: Stark
            description: User's last name
          createdAt:
            type: string
            format: date-time
            description: User's date creation
            example: 2022-02-16T09:12:32.766+00:00
          updatedAt:
            type: string
            format: date-time
            description: User's date update
            example: 2022-02-16T09:12:32.766+00:00
          id:
            type: string
            format: uuid
            description: User's UUID
            example: 620cc0003724e10c821cfb56
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        example: Transactions successfully retrieved!
      transactions:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uuid
              description: This transaction's UUID
              example: 620cc0003724e10c821cfb55
            date:
              type: string
              format: date-time
              description: The date at which this transaction has been effectued
              example: 2022-02-16T09:12:32.766+00:00
            description:
              type: string
              description: This transaction description (recipient name)
              example: Golden Sun Bakery
            amount:
              type: integer
              description: The sum which has been payed by the user in cents
              example: 50
            balance:
              type: integer
              description: This account balance after payment in cents
              example: 208979
            type:
              type: string
              description: The method used by the user in order to pay (electronic, cash, etc...)
              example: Electronic
            category:
              type: string
              description: The category of this transaction (Food | Personal | etc...)
              example: Food
            notes:
              type: string
              description: Note added by the user. Default is empty.
              example: Chocolatine
  TransactionUpdateRequest:
    type: object
    properties:
      id:
        type: string
        format: uuid
        description: The UUID of the transaction that need to be updated
        example: 620cc0005784e10c821cfb33
      category:
        type: string
        description: The new category of this transaction
        example: Deposit
      notes:
        type: string
        description: Note added by the user.
        example: Salary
  TransactionUpdateResponse:
    type: object
    properties:
      status:
        type: integer
        description: Response status code from the API
        example: 200
      message:
        type: string
        description: Response message from the API
        example: Transaction successfully updated!
      transaction:
        type: object
        properties:
          id:
            type: string
            format: uuid
            description: The UUID of the transaction that need to be updated
            example: 620cc0005784e10c821cfb33
          category:
            type: string
            description: The new category of this transaction
            example: Deposit
          notes:
            type: string
            description: Note added by the user.
            example: Salary